### PR TITLE
Parse JS SDK 1.8.2

### PR DESCRIPTION
**Pull request by minhnc**

### CODE REVIEW

**Comment by gimdongwoo** [comment]
Thank you! I will review and merge to soon.

**Comment by minhnc** [comment]
cool.. my pleasure :)

**Comment by gimdongwoo** [comment]
Sorry, I'm late. Thanks for your PR!

And I updated error handler code for correct error message.

e.code & e.message is received from Parse server.

**Comment by minhnc** [comment]
cool!

**Pull request merged**
